[package]
name = "graphql-macros"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
license = "Apache-2.0/MIT"

[lib]
proc-macro = true

[dependencies]
log = "0.4"
graphql = { path = "../graphql" }
rustfmt-nightly = { version = "0.3" , optional = true }

[features]
default = []
rustfmt = ["rustfmt-nightly"]

